sonar.organization=lincoyan2311-pixel
sonar.projectKey=lincoyan2311-pixel_sistema-pacientes-seguro
sonar.projectName=Sistema Pacientes Seguro
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=tests/**,venv/**,.venv/**,__pycache__/**,.pytest_cache/**,datos/**,htmlcov/**

sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=reporte-bandit.json