sonar.projectKey=sistema-pacientes-seguro
sonar.projectName=Sistema Pacientes Seguro
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=venv/**,.venv/**,__pycache__/**,.pytest_cache/**,datos/**,htmlcov/**
sonar.python.coverage.reportPaths=coverage.xml
