name: Pruebas y SonarQube Cloud

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: python -m pip install bandit==1.9.4 pytest==8.4.2 pytest-cov==7.0.0

      - name: Ejecutar pruebas y cobertura
        run: python -m pytest --cov=. --cov-report=xml --cov-report=term-missing

      - name: Ejecutar Bandit
        run: python -m bandit -r . -x "./tests" -f json -o reporte-bandit.json --exit-zero

      - name: Analizar con SonarQube Cloud
        uses: SonarSource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2 # v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
